#!/usr/bin/env bash
set -euo pipefail

# --- config ---
RELOCATE_ROOT="${RELOCATE_ROOT:-/mnt/noir/scratch/relocate}"

# --- helpers ---

# Find all Rust target dirs under a search dir.
# Prints: size<TAB>path  (sorted by size descending)
find_target_dirs() {
  local search_dir="$1"
  while IFS= read -r target_dir; do
    local parent_dir
    parent_dir="$(dirname "$target_dir")"
    if [ -f "$parent_dir/Cargo.toml" ]; then
      local size
      size=$(du -sh "$target_dir" | cut -f1)
      printf '%s\t%s\n' "$size" "$target_dir"
    fi
  done < <(find "$search_dir" -type d -name target)
}

# Convert a human-readable size (e.g. 14G, 590M, 1.7G) to bytes for summing.
size_to_bytes() {
  local size="$1"
  local num unit
  num=$(echo "$size" | grep -oP '[\d.]+')
  unit=$(echo "$size" | grep -oP '[A-Z]' | head -1)
  case "$unit" in
    K) echo "$num" | awk '{print $1 * 1024}' ;;
    M) echo "$num" | awk '{print $1 * 1024 * 1024}' ;;
    G) echo "$num" | awk '{print $1 * 1024 * 1024 * 1024}' ;;
    T) echo "$num" | awk '{print $1 * 1024 * 1024 * 1024 * 1024}' ;;
    *) echo "$num" | awk '{print $1}' ;;
  esac
}

# Convert bytes to a human-readable string.
bytes_to_human() {
  local bytes="$1"
  if [ "$bytes" -ge 1073741824 ]; then
    awk -v b="$bytes" 'BEGIN {printf "%.1fG", b / 1073741824}'
  elif [ "$bytes" -ge 1048576 ]; then
    awk -v b="$bytes" 'BEGIN {printf "%.1fM", b / 1048576}'
  elif [ "$bytes" -ge 1024 ]; then
    awk -v b="$bytes" 'BEGIN {printf "%.1fK", b / 1024}'
  else
    echo "${bytes}B"
  fi
}

# --- subcommand: sizes ---
cmd_sizes() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: $0 sizes <directory>"
    exit 1
  fi
  local search_dir
  search_dir="$(realpath "$1")"
  if [ ! -d "$search_dir" ]; then
    echo "❌ Directory does not exist: $search_dir"
    exit 1
  fi
  find_target_dirs "$search_dir" | sort -rh
}

# --- subcommand: relocate ---
cmd_relocate() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: $0 relocate <directory>"
    exit 1
  fi
  local search_dir
  search_dir="$(realpath "$1")"
  if [ ! -d "$search_dir" ]; then
    echo "❌ Directory does not exist: $search_dir"
    exit 1
  fi

  # Collect target dirs, sorted by size descending
  local results
  results=$(find_target_dirs "$search_dir" | sort -rh)

  if [ -z "$results" ]; then
    echo "No Rust target directories found."
    exit 0
  fi

  # Compute total size
  local total_bytes=0
  while IFS=$'\t' read -r size path; do
    total_bytes=$(awk -v t="$total_bytes" -v s="$(size_to_bytes "$size")" 'BEGIN {print t + s}')
  done <<< "$results"
  local total_human
  total_human=$(bytes_to_human "$total_bytes")

  # Show what will be relocated
  echo "Found $(echo "$results" | wc -l) target directory(ies):"
  echo "$results"
  echo ""
  echo "Total size to relocate: $total_human"
  echo ""
  echo "Dry run by default. This will:"
  echo "  1. rsync each target dir to $RELOCATE_ROOT/<path>"
  echo "  2. mv the original to <path>.bak"
  echo "  3. symlink $RELOCATE_ROOT/<path> back in place"
  echo ""
  printf 'Proceed? [y/N] '
  read -r answer
  case "$answer" in
    y|yes|Y|YES) ;;
    *) echo "Aborted."; exit 0 ;;
  esac

  # Execute relocation
  local bak_dirs=()
  while IFS=$'\t' read -r size path; do
    if [ -L "$path" ]; then
      echo "⏭️  Skipping (already a symlink): $path"
      continue
    fi
    echo "📦 Relocating: $path ($size)"

    local rel_path="${path#/}"
    local new_dir="$RELOCATE_ROOT/$rel_path"

    # Ensure the relocate destination parent exists
    mkdir -p "$new_dir"

    # rsync the target dir contents into the new location
    rsync -avPS "$path/" "$new_dir/"

    # Move original to .bak
    mv "$path" "${path}.bak"
    bak_dirs+=("${path}.bak")

    # Create symlink in place
    ln -s "$new_dir" "$path"

    echo "✅ Done: $path -> $new_dir"
  done <<< "$results"

  echo ""
  echo "Relocation complete. Total relocated: $total_human"

  # Generate optional cleanup script
  if [ "${#bak_dirs[@]}" -gt 0 ]; then
    local clean_script="/tmp/relocate-clean.sh"
    {
      echo "#!/usr/bin/env bash"
      echo "# Auto-generated by target-sizes.sh"
      echo "# Removes the .bak directories left behind by relocation."
      echo "# Review before running!"
      echo "set -euo pipefail"
      echo ""
      for bak in "${bak_dirs[@]}"; do
        echo "rm -rf \"$bak\""
      done
    } > "$clean_script"
    chmod +x "$clean_script"
    echo ""
    echo "Cleanup script written to: $clean_script"
    echo "Run it to remove the .bak directories."
  fi
}

# --- main dispatch ---
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <sizes|relocate> <directory>"
  exit 1
fi

subcmd="$1"
shift

case "$subcmd" in
  sizes)   cmd_sizes "$@" ;;
  relocate) cmd_relocate "$@" ;;
  *)
    echo "Unknown subcommand: $subcmd"
    echo "Usage: $0 <sizes|relocate> <directory>"
    exit 1
    ;;
esac
